[providers]
java = "17"

[phases.setup]
nixPkgs = ["python3", "python3Packages.pip"]

[phases.install]
cmds = [
    "chmod +x install-python.sh",
    "./install-python.sh",
    "chmod +x ./mvnw"
]

[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"