[build]
builder = "nixpacks"

[deploy]
startCommand = "./mvnw spring-boot:run"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
JAVA_VERSION = "17"
PYTHON_VERSION = "3.11" 