[build]
builder = "dockerfile"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
JAVA_VERSION = "17"
PYTHON_VERSION = "3.11"
SPRING_PROFILES_ACTIVE = "prod" 