[build]
builder = "nixpacks"

[deploy]
startCommand = "./mvnw spring-boot:run -Dspring-boot.run.profiles=prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
JAVA_VERSION = "17"
SPRING_PROFILES_ACTIVE = "prod" 