# Configuración específica para DESARROLLO
spring:
  # JPA - Modo desarrollo con logs detallados
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Sin cache para desarrollo (cambios rápidos)
        cache:
          use_second_level_cache: false
          use_query_cache: false

# Logging detallado para desarrollo
logging:
  level:
    com.desafios.admision_mtn: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# DevTools habilitado
spring.devtools:
  restart:
    enabled: true
  livereload:
    enabled: true